[package]
name = "cell-node"
version.workspace = true
edition.workspace = true
license-file.workspace = true
[dependencies]
cell-model.workspace = true
cell-engine.workspace = true
cell-rune.workspace = true
cybergraph.workspace = true

[features]
legacy-redb-migration = ["cybergraph/legacy-redb-migration"]
